-- MySQL Script generated by MySQL Workbench
-- qua 25 nov 2020 18:04:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NULL,
  `passwd` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `start_time` TIMESTAMP(20) NULL,
  `end_time` TIMESTAMP(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teach` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_Teach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_Teach` (
  `id` INT NOT NULL,
  `course_id` INT NULL,
  `teach_id` INT NULL,
  `Course_id` INT NOT NULL,
  `Teach_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Course_id`, `Teach_id`),
  INDEX `fk_Course_Teach_Course_idx` (`Course_id` ASC) VISIBLE,
  INDEX `fk_Course_Teach_Teach1_idx` (`Teach_id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Teach_Course`
    FOREIGN KEY (`Course_id`)
    REFERENCES `mydb`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Teach_Teach1`
    FOREIGN KEY (`Teach_id`)
    REFERENCES `mydb`.`Teach` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `id` INT NOT NULL,
  `number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_Room` (
  `id` INT NOT NULL,
  `course_id` INT NULL,
  `room_id` INT NULL,
  `Room_id` INT NOT NULL,
  `Course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Room_id`, `Course_id`),
  INDEX `fk_Course_Room_Room1_idx` (`Room_id` ASC) VISIBLE,
  INDEX `fk_Course_Room_Course1_idx` (`Course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Room_Room1`
    FOREIGN KEY (`Room_id`)
    REFERENCES `mydb`.`Room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_Room_Course1`
    FOREIGN KEY (`Course_id`)
    REFERENCES `mydb`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
